# Generated by Django 3.0.8 on 2020-07-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_duesness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='duesness',
            new_name='dueness',
        ),
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.TextField(default='notStarted'),
        ),
    ]
